language: cpp
sudo: required

python:
    - "3.4"
    # - "2.7"

addons:
    apt:
        packages:
            - cmake
            - libeigen3-dev
            - libboost-all-dev
            - libboost-python-dev
            - python-numpy
            - python3-numpy

install:
    - cd $TRAVIS_BUILD_DIR
    - mkdir build
    - cd build
    # - cmake -DBUILD_PYTHON_INTERFACE=ON -DBUILD_USE_PYTHON3=OFF ..
    - cmake -DBUILD_PYTHON_INTERFACE=ON ..
    - make
    - sudo make install

script:
    - cd $TRAVIS_BUILD_DIR/build
    - ./cluster_test
    - ./scluster_test
    - ./mcluster_test
    - sudo ldconfig
    - cd ../python
    - python3 testapi.py
